module.exports = {
  apps: [
    {
      name: 'shares-backend',
      script: 'python3',
      args: 'dashboard/backend/server.py',
      cwd: '/home/psardar/Scripts/SharesCalculations',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 3000,
      out_file: './logs/backend-out.log',
      error_file: './logs/backend-err.log',
      merge_logs: true,
      env: {
        PORT: 8080,
      },
    },
    {
      name: 'shares-dashboard',
      script: 'npx',
      args: 'ng serve --port 4201 --host 0.0.0.0',
      cwd: '/home/psardar/Scripts/SharesCalculations/dashboard',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_restarts: 10,
      restart_delay: 5000,
      out_file: '/home/psardar/Scripts/SharesCalculations/logs/dashboard-out.log',
      error_file: '/home/psardar/Scripts/SharesCalculations/logs/dashboard-err.log',
      merge_logs: true,
    },
  ],
};
